### ISSUE TITLE
Typings?

### ISSUE THREAD

**Issue by douglasg14b** [uber/geojson2h3#15]
Can a typings file be generated for this project to support intellisense & TypeScript?

**Example:**

```ts
declare module 'geojson2h3' {
    import { Feature } from 'geojson';

    export function featureToH3Set(feature: Feature, resolution: number): string[];
    export function h3ToFeature(hexAddress: string, properties: Record<string, string | number | boolean>): Feature;
    export function h3SetToFeature(hexagons: string[], properties: Record<string, string | number | boolean>): Feature;
    export function h3SetToMultiPolygonFeature(hexagons: string[], properties: Record<string, string | number | boolean>): Feature;
    export function h3SetToFeatureCollection(hexagons: string[], getProperties: (hexAddress: string) => Record<string, string | number | boolean>): string[];
}
```

The example are what I assume the typings might be, maintainers will probably have a better idea for the `properties` args at least.

**Comment by nrabinowitz** [comment]
Thanks, this is a great suggestion. I haven't touched this library in a while, but I see if I can add this in.

**Comment by douglasg14b** [comment]
These are the typing I augmented in my local codebase .My assumptions on some of the  may be incorrect, please provide the preferred types.

The typings can be submitted to https://github.com/DefinitelyTyped/DefinitelyTyped as an alternative to adding them to this repo directly.

**Comment by matthiasfeist** [comment]
should be as easy as adding a index.d.ts file to this repo :) 
@nrabinowitz how far have you come? If you're not already working on it, I'm happy to submit a PR for this

**Comment by nrabinowitz** [comment]
Sorry, I'd forgotten to follow up here. PR up now: #16

**Comment by nrabinowitz** [comment]
Published in https://www.npmjs.com/package/geojson2h3 - it would be great if someone could confirm that the typings work properly here in a TS project.

**Comment by matthiasfeist** [comment]
I just installed the latest version and removed my own type file and **I can confirm that it works**

**Comment by nrabinowitz** [comment]
Awesome, thanks for the confirmatiion @matthiasfeist !
