### ISSUE TITLE
Java bindings for geojson2h3?

### ISSUE THREAD

**Issue by InfoDevkota** [uber/geojson2h3#27]
Is there any library that I can use on Java

**Comment by nrabinowitz** [comment]
Not to my knowledge. Note however that `geojson2h3` is a fairly light wrapper - using `h3-java` with any Java library that can handle GeoJSON should allow you to perform the same operations fairly easily.

**Comment by InfoDevkota** [comment]
We were trying to move the h3 to Feature from our backend to android side. I was looking for the library to suggest to android team. Going through the source code, Looks like we can achieve that with `h3-java`. Thank you!
