### ISSUE TITLE
h3SetToFeature returns misshaped MultiPolygon

### ISSUE THREAD

**Issue by Stophface** [uber/geojson2h3#32]
I am getting a strange result when using `h3SetToFeature`.
This are the hashes (resolution 10) I am passing to the `h3SetToFeature`.

    let h3Hashes = ["8a2834745127fff","8a2834745127fff","8a2834745127fff","8a283474512ffff","8a283474512ffff","8a283474512ffff","8a2834745177fff","8a2834745177fff","8a2834745177fff","8a2834745147fff","8a2834745147fff","8a2834745147fff","8a283474514ffff","8a283474514ffff","8a283474514ffff","8a2834745a97fff","8a2834745a97fff","8a2834745a97fff","8a2834745a9ffff","8a2834745a9ffff","8a2834745a9ffff","8a2834745337fff","8a2834745327fff","8a2834745327fff","8a2834745307fff","8a283474532ffff","8a283474530ffff","8a283474530ffff","8a2834745377fff","8a2834745357fff","8a2834745357fff","8a2834745357fff","8a283474535ffff","8a283474535ffff","8a283474535ffff","8a2834745267fff","8a2834745267fff","8a2834745267fff","8a283474526ffff","8a283474526ffff","8a283474526ffff","8a283476a537fff","8a283476a537fff","8a283476a537fff","8a283476a507fff","8a283476a507fff","8a283476a507fff","8a283476a50ffff","8a283476a50ffff","8a283476a577fff","8a283476a577fff","8a283476a547fff","8a283476a547fff","8a283476a547fff","8a283476a54ffff","8a283476a54ffff","8a283476a0b7fff","8a283476a0b7fff","8a283476a087fff","8a283476a087fff","8a283476a087fff","8a283476a08ffff","8a283476a08ffff","8a2834744987fff","8a28347448c7fff","8a28347448dffff","8a28347448dffff","8a28347448dffff","8a2834744167fff","8a2834744167fff","8a2834744167fff","8a2834744147fff","8a283474416ffff"];

Here is function call

    const result = geojson2h3.h3SetToFeature(h3Hashes);

And the `stringyfied` result is this

`{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[-122.177128570058,37.39595330141493],[-122.177333429289,37.39662671070871],[-122.17817720593614,37.39679411426042],[-122.17838207218551,37.39746751464813],[-122.17922585163717,37.39763490685678],[-122.17943072490492,37.398308298337966],[-122.18027450716059,37.39847567920331],[-122.18047938744664,37.39914906177764],[-122.18132317250576,37.399316431299454],[-122.18152805981013,37.39998980496648],[-122.1823718476721,37.40015716314454],[-122.177128570058,37.39595330141493]]],[[[-122.17922585163717,37.39763490685678],[-122.17943072490492,37.398308298337966],[-122.17922585163717,37.39763490685678]]],[[[-122.18047938744664,37.39914906177764],[-122.18047938744664,37.39914906177764]]],[[[-122.18152805981013,37.39998980496648],[-122.18088915512129,37.4004958129059],[-122.18109404250993,37.401169181459544],[-122.1819378415216,37.40133653827952],[-122.18214273592875,37.4020098979252],[-122.18298653774308,37.402177243400935],[-122.18319143916875,37.40285059413825],[-122.18403524378516,37.40301792826948],[-122.18424015222928,37.403691270098044],[-122.18508395964724,37.40385859288454],[-122.18528887510988,37.40453192580398],[-122.18613268532881,37.404699237245524],[-122.1863376078099,37.40537256125544],[-122.1871814208293,37.405539861351755],[-122.18738635032881,37.406213176451764],[-122.1882301661481,37.40638046520265],[-122.18843510266606,37.40705377139234],[-122.18927892128468,37.40722104879754],[-122.18948386482107,37.40789434607652],[-122.19032768623849,37.4080616121358],[-122.19053263679324,37.40873490050372],[-122.1913764610089,37.40890215521684],[-122.19201532351721,37.4083961229223],[-122.19285913937777,37.408563367649556],[-122.1930641038827,37.40923664331079],[-122.19390792254015,37.409403876691655],[-122.1941128940632,37.410077143440944],[-122.1949567155169,37.410244365475194],[-122.19559555429423,37.409738322121285],[-122.1964393673902,37.40990553417007],[-122.19664435286215,37.41057878821134],[-122.19748816875298,37.410745988913284],[-122.19769316124287,37.411419234041716],[-122.198536979928,37.41158642339658],[-122.19917579496925,37.41108036898498],[-122.19897079554929,37.41040712765257],[-122.1981269880181,37.41023993693571],[-122.1979219956158,37.40956668669037],[-122.1970781908786,37.409399484626654],[-122.19687320549399,37.40872622546877],[-122.19602940355135,37.40855901205846],[-122.19539057584014,37.40906505916757],[-122.19454676553963,37.40889783577216],[-122.19434179410345,37.40822456390639],[-122.1934979865989,37.40805732916462],[-122.19329302218068,37.407384048387186],[-122.19244921747267,37.407216802299274],[-122.19181036603044,37.40772283834949],[-122.19096655296723,37.40755558227609],[-122.19076160249864,37.40688228879209],[-122.18991779223337,37.40671502137279],[-122.18971284878297,37.40604171897801],[-122.18886904131618,37.405874440213026],[-122.18866410488397,37.40520112890786],[-122.18782030021623,37.40503383879744],[-122.18761537080226,37.404360518582244],[-122.18677156893408,37.40419321712663],[-122.18656664653834,37.40351988800181],[-122.18572284747032,37.403352575201254],[-122.1855179320928,37.402679237167206],[-122.18615680885031,37.40217321572855],[-122.18595189355804,37.401499872580395],[-122.1851081084411,37.40133254707616],[-122.18490320016683,37.40065919501948],[-122.18405941785082,37.400491858171016],[-122.18385451659462,37.399818497206184],[-122.18301073708012,37.39965114901371],[-122.18280584284199,37.39897777914111],[-122.18196206612947,37.398810419604885],[-122.18175717890946,37.39813704082493],[-122.18091340499953,37.39796966994516],[-122.18070852479762,37.397296282258225],[-122.17986475369081,37.39712890003518],[-122.17965988050702,37.39645550344166],[-122.1788161122039,37.39628810987554],[-122.17861124603826,37.39561470437583],[-122.17776748053932,37.39544729946691],[-122.17756262139186,37.3947738850614],[-122.17671885869773,37.39460646880989],[-122.1765140065684,37.39393304549897],[-122.17567024667959,37.39376561790513],[-122.17503132777263,37.39427161497894],[-122.17523617296689,37.39494504208376],[-122.17607994400329,37.395112468320896],[-122.17628479621592,37.39578588652039],[-122.18152805981013,37.39998980496648]]],[[[-122.18738635032881,37.406213176451764],[-122.18738635032881,37.406213176451764]]],[[[-122.18843510266606,37.40705377139234],[-122.18843510266606,37.40705377139234]]],[[[-122.18948386482107,37.40789434607652],[-122.18948386482107,37.40789434607652]]],[[[-122.17671885869773,37.39460646880989],[-122.17671885869773,37.39460646880989]]],[[[-122.17671885869773,37.39460646880989],[-122.17607994400329,37.395112468320896],[-122.17628479621592,37.39578588652039],[-122.17671885869773,37.39460646880989]]],[[[-122.1836254340001,37.40167123058925],[-122.1836254340001,37.40167123058925]]],[[[-122.18467413582546,37.40251191302192],[-122.18403524378516,37.40301792826948],[-122.18424015222928,37.403691270098044],[-122.18467413582546,37.40251191302192]]],[[[-122.19053263679324,37.40873490050372],[-122.1913764610089,37.40890215521684],[-122.19201532351721,37.4083961229223],[-122.19053263679324,37.40873490050372]]],[[[-122.17756262139186,37.3947738850614],[-122.17756262139186,37.3947738850614]]],[[[-122.17776748053932,37.39544729946691],[-122.17776748053932,37.39544729946691]]],[[[-122.17776748053932,37.39544729946691],[-122.17776748053932,37.39544729946691]]],[[[-122.17986475369081,37.39712890003518],[-122.17965988050702,37.39645550344166],[-122.1788161122039,37.39628810987554],[-122.17986475369081,37.39712890003518]]],[[[-122.17986475369081,37.39712890003518],[-122.17986475369081,37.39712890003518]]],[[[-122.18342053265911,37.40099787473794],[-122.18405941785082,37.400491858171016],[-122.18342053265911,37.40099787473794]]],[[[-122.1844692274662,37.40183856607904],[-122.1844692274662,37.40183856607904]]],[[[-122.18572284747032,37.403352575201254],[-122.1855179320928,37.402679237167206],[-122.18572284747032,37.403352575201254]]],[[[-122.1855179320928,37.402679237167206],[-122.1855179320928,37.402679237167206]]],[[[-122.18677156893408,37.40419321712663],[-122.18656664653834,37.40351988800181],[-122.18572284747032,37.403352575201254],[-122.18677156893408,37.40419321712663]]],[[[-122.18782030021623,37.40503383879744],[-122.18761537080226,37.404360518582244],[-122.18677156893408,37.40419321712663],[-122.18782030021623,37.40503383879744]]],[[[-122.18782030021623,37.40503383879744],[-122.18782030021623,37.40503383879744]]],[[[-122.18070852479762,37.397296282258225],[-122.18070852479762,37.397296282258225]]],[[[-122.18196206612947,37.398810419604885],[-122.18196206612947,37.398810419604885]]],[[[-122.18091340499953,37.39796966994516],[-122.18091340499953,37.39796966994516]]],[[[-122.18301073708012,37.39965114901371],[-122.18280584284199,37.39897777914111],[-122.18196206612947,37.398810419604885],[-122.18301073708012,37.39965114901371]]],[[[-122.18886904131618,37.405874440213026],[-122.18866410488397,37.40520112890786],[-122.18886904131618,37.405874440213026]]],[[[-122.18991779223337,37.40671502137279],[-122.18971284878297,37.40604171897801],[-122.18886904131618,37.405874440213026],[-122.18991779223337,37.40671502137279]]],[[[-122.19096655296723,37.40755558227609],[-122.19076160249864,37.40688228879209],[-122.18991779223337,37.40671502137279],[-122.19096655296723,37.40755558227609]]],[[[-122.1930641038827,37.40923664331079],[-122.1930641038827,37.40923664331079]]],[[[-122.19181036603044,37.40772283834949],[-122.19181036603044,37.40772283834949]]],[[[-122.1941128940632,37.410077143440944],[-122.1941128940632,37.410077143440944]]],[[[-122.1934979865989,37.40805732916462],[-122.1934979865989,37.40805732916462]]],[[[-122.19454676553963,37.40889783577216],[-122.19434179410345,37.40822456390639],[-122.1934979865989,37.40805732916462],[-122.19454676553963,37.40889783577216]]],[[[-122.19559555429423,37.409738322121285],[-122.19559555429423,37.409738322121285]]],[[[-122.1970781908786,37.409399484626654],[-122.1970781908786,37.409399484626654]]],[[[-122.1981269880181,37.41023993693571],[-122.1979219956158,37.40956668669037],[-122.1970781908786,37.409399484626654],[-122.1981269880181,37.41023993693571]]],[[[-122.19897079554929,37.41040712765257],[-122.19897079554929,37.41040712765257]]],[[[-122.15332239701078,37.388062915920955],[-122.1541661954517,37.388230536821816],[-122.1548052633357,37.38772460749431],[-122.15564905345059,37.3878922184067],[-122.1562881060672,37.387386282882005],[-122.15608337277192,37.3867127388844],[-122.15523959380059,37.38654512662028],[-122.15503486752502,37.38587157372252],[-122.15419109137076,37.38570395011885],[-122.15398637211489,37.385030388321326],[-122.15462542207251,37.38452445391869],[-122.15442070289552,37.38385088701296],[-122.15357694070163,37.38368325071868],[-122.1529378865421,37.384189182681475],[-122.15314259877827,37.38486275337838],[-122.15250353355472,37.385368681584204],[-122.15270824586943,37.38604224717274],[-122.15355203034899,37.38620988076446],[-122.15375674968362,37.38688343745332],[-122.15332239701078,37.388062915920955]]],[[[-122.15311767759742,37.387389364341274],[-122.15311767759742,37.387389364341274]]],[[[-122.15375674968362,37.38688343745332],[-122.15375674968362,37.38688343745332]]],[[[-122.15419109137076,37.38570395011885],[-122.15398637211489,37.385030388321326],[-122.15419109137076,37.38570395011885]]],[[[-122.15419109137076,37.38570395011885],[-122.15419109137076,37.38570395011885]]],[[[-122.14938311359745,37.38031823554603],[-122.1502268645166,37.38048591719414],[-122.15086592021505,37.379979988795526],[-122.15066122919431,37.379306381189345],[-122.14981748941645,37.37913869819074],[-122.14917842951814,37.379644624148845],[-122.14938311359745,37.38031823554603]]],[[[-122.15398637211489,37.385030388321326],[-122.15398637211489,37.385030388321326]]],[[[-122.15523959380059,37.38654512662028],[-122.15503486752502,37.38587157372252],[-122.15523959380059,37.38654512662028]]],[[[-122.18319143916875,37.40285059413825],[-122.18319143916875,37.40285059413825]]],[[[-122.177333429289,37.39662671070871],[-122.177333429289,37.39662671070871]]],[[[-122.17838207218551,37.39746751464813],[-122.17838207218551,37.39746751464813]]],[[[-122.18528887510988,37.40453192580398],[-122.18528887510988,37.40453192580398]]],[[[-122.1863376078099,37.40537256125544],[-122.1863376078099,37.40537256125544]]]]}}`

Passing the result here https://geojsonlint.com/ I get the following errors

~40 of these
> Line 1: a LinearRing of coordinates needs to have four or more positions

and 1 of this
> Line 1: Polygons and MultiPolygons should follow the right-hand rule

This is how the result looks like (https://geojson.tools/, geojosn.io won't even display it):
<img width="710" alt="Screenshot 2023-02-19 at 18 19 08" src="https://user-images.githubusercontent.com/8275981/219963884-7c7d3b7b-d15c-4e36-ba9b-8c21052bf1bc.png">

What is happening here?

**Comment by Stophface** [comment]
I had duplicates in my `h3hashes` array!

**Comment by nrabinowitz** [comment]
Yes, I was about to respond: 
```
const set = new Set(h3Hashes);
set.size; // 32
h3Hashes.length; // 73
```
The output of `h3ToMultiPolygon` is undefined with duplicates in the input.

**Comment by Stophface** [comment]
@nrabinowitz  Yeah sorry. I checked everything but this and then after posting, I realized that this might be the problem.
